# =============================================================================
# ChatVista Backend - Digital Ocean App Platform Specification
# Deploy using: doctl apps create --spec .do/app.yaml
# =============================================================================

name: chatvista-backend
region: nyc
features:
  - buildpack-stack=ubuntu-22

# =============================================================================
# Services
# =============================================================================

services:
  - name: api
    github:
      repo: yourusername/chatvista
      branch: main
      deploy_on_push: true
    source_dir: apps/backend
    dockerfile_path: apps/backend/Dockerfile
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: professional-xs
    
    # HTTP configuration
    http_port: 4000
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
    
    # Environment variables
    envs:
      # Application
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: APP_NAME
        value: ChatVista
      - key: APP_URL
        value: ${APP_URL}
      - key: API_URL
        value: ${_self.PUBLIC_URL}
      
      # Database (Digital Ocean Managed PostgreSQL)
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      
      # Redis (Digital Ocean Managed Redis)
      - key: REDIS_URL
        value: ${redis.DATABASE_URL}
      
      # JWT Secrets (set via doctl or dashboard)
      - key: JWT_SECRET
        type: SECRET
        value: ${JWT_SECRET}
      - key: JWT_REFRESH_SECRET
        type: SECRET
        value: ${JWT_REFRESH_SECRET}
      - key: SESSION_SECRET
        type: SECRET
        value: ${SESSION_SECRET}
      
      # Encryption Keys
      - key: ENCRYPTION_KEY
        type: SECRET
        value: ${ENCRYPTION_KEY}
      - key: SIGNING_KEY
        type: SECRET
        value: ${SIGNING_KEY}
      
      # Digital Ocean Spaces
      - key: DO_SPACES_ENDPOINT
        value: https://nyc3.digitaloceanspaces.com
      - key: DO_SPACES_REGION
        value: nyc3
      - key: DO_SPACES_BUCKET
        value: chatvista-storage
      - key: DO_SPACES_ACCESS_KEY
        type: SECRET
        value: ${DO_SPACES_ACCESS_KEY}
      - key: DO_SPACES_SECRET_KEY
        type: SECRET
        value: ${DO_SPACES_SECRET_KEY}
      - key: DO_SPACES_CDN_ENDPOINT
        value: https://chatvista-storage.nyc3.cdn.digitaloceanspaces.com
      
      # CORS
      - key: CORS_ORIGINS
        value: ${FRONTEND_URL}
      
      # OpenAI (optional)
      - key: OPENAI_API_KEY
        type: SECRET
        value: ${OPENAI_API_KEY}
      
      # SMTP
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        type: SECRET
        value: ${SMTP_USER}
      - key: SMTP_PASSWORD
        type: SECRET
        value: ${SMTP_PASSWORD}
      - key: SMTP_FROM_EMAIL
        value: noreply@chatvista.app
      
      # Feature Flags
      - key: ENABLE_AI_TRANSCRIPTION
        value: "true"
      - key: ENABLE_RECORDING
        value: "true"
      - key: ENABLE_AUDIT_LOGGING
        value: "true"
      
      # Local Storage Path
      - key: CHATVISTA_STORAGE_PATH
        value: /app/storage

    # Resource limits
    run_command: node dist/index.js
    build_command: pnpm install && pnpm build

# =============================================================================
# Databases
# =============================================================================

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb
    num_nodes: 1
    
  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb
    num_nodes: 1

# =============================================================================
# Alerts
# =============================================================================

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: CPU_UTILIZATION
    value: 80
    operator: GREATER_THAN
    window: FIVE_MINUTES
  - rule: MEM_UTILIZATION
    value: 80
    operator: GREATER_THAN
    window: FIVE_MINUTES
  - rule: RESTART_COUNT
    value: 5
    operator: GREATER_THAN
    window: TEN_MINUTES
